#!/bin/sh

BIN=`basename "$0" | sed 's/_wrap$//'`

#id=`date +%y%m%d%H%M%S`
#$DEBUGGER $BIN $ARGS 2>&1 | tee `pwd`/testrun-$id
#echo Output saved in `pwd`/testrun-$id

if [ -z "$DEBUGGER" ]
then
	tests/$BIN $ARGS
else
	$DEBUGGER tests/.libs/lt-$BIN $ARGS
fi
