#!/bin/bash -ue

SRCHRV=tmp1/H:MSG2:HRV:201001191200
SRCIR16=tmp1/H:MSG2:IR_016:201001191200
FILEHRV=hrv.grd
FILEIR16=ir16.grd
# Coast resolution (l=low, h=high, f=full)
COASTRES=l

## Export collimating HRV and IR_016
#tools/msat --gdt --reproject=latlon --resize=400,300 --Area=36,39,12,16.5 tmp1/H:MSG1:HRV:200611130800
#tools/msat --gdt --reproject=latlon --resize=400,300 --Area=36,39,12,16.5 tmp1/H:MSG1:IR_016:200611130800

do_reproject() {
	OPTS="$1"
	rm -f tmp1.tiff tmp2.tiff
	gdalwarp -t_srs "+proj=latlong" -of GTiff $OPTS $SRCHRV tmp1.tiff
	gdal_translate -of GMT tmp1.tiff $FILEHRV
	gdalwarp -t_srs "+proj=latlong" -of GTiff $OPTS $SRCIR16 tmp2.tiff
	gdal_translate -of GMT tmp2.tiff $FILEIR16
	rm -f tmp1.tiff tmp2.tiff

	RANGE=$(gdalinfo -stats $FILEHRV|awk -F'[ =,]' '/Minimum=/{ printf 0+$4 "/" 0+$7 "/1" }')
	GMT makecpt -Cgray -T$RANGE > $FILEHRV.cpt
	RANGE=$(gdalinfo -stats $FILEIR16|awk -F'[ =,]' '/Minimum=/{ printf 0+$4 "/" 0+$7 "/1" }')
	GMT makecpt -Cgray -T83/656/1 > $FILEIR16.cpt
}

do_reproject "-te 12 36 16.5 39 -ts 400 300"

OUT=testsicily.ps

GMT gmtset GRID_CROSS_SIZE 1 ANNOT_FONT_SIZE_PRIMARY 10

GMT psbasemap -R12/16.5/36/39 -Jm1i -B0 -P -K -U"Sicily test" > $OUT
GMT grdimage -Q -R $FILEHRV -C$FILEHRV.cpt -J -O -K >> $OUT
GMT pscoast -R12/16.5/36/39 -Jm1i -O -K -Bg30 -D$COASTRES -Wlightgray >> $OUT
echo 14.25 39.2 12 0 0 CM $FILEHRV | \
	GMT pstext -J -R -O -K -N >> $OUT

GMT grdimage -Q -R $FILEIR16 -Y5i -C$FILEIR16.cpt -J -O -K >> $OUT
GMT pscoast -R12/16.5/36/39 -Jm1i -O -K -Bg30 -D$COASTRES -Wlightgray >> $OUT
echo 14.25 39.2 12 0 0 CM $FILEIR16 | \
	GMT pstext -J -R -O -N >> $OUT

# No -K on the last one to close the graphic context

## Export collimating HRV and IR_016
#tools/msat --gdt --reproject=latlon --resize=400,300 --Area=23,27,32,40 tmp1/H:MSG1:HRV:200611130800
#tools/msat --gdt --reproject=latlon --resize=400,300 --Area=23,27,32,40 tmp1/H:MSG1:IR_016:200611130800
do_reproject "-te 32 23 40 27 -ts 400 300"

OUT=testredsea.ps

GMT gmtset GRID_CROSS_SIZE 1 ANNOT_FONT_SIZE_PRIMARY 10

GMT psbasemap -R32/40/23/27 -Jm0.8i -B0 -P -K -U"Red sea test" > $OUT
GMT grdimage -Q -R $FILEHRV -C$FILEHRV.cpt -J -O -K >> $OUT
GMT pscoast -R -J -O -K -Bg30 -D$COASTRES -Wlightgray -Ir >> $OUT
echo 35 27.3 12 0 0 CM $FILEHRV | \
	GMT pstext -J -R -O -K -N >> $OUT

GMT grdimage -Q -R $FILEIR16 -Y5i -C$FILEIR16.cpt -J -O -K >> $OUT
GMT pscoast -R -J -O -K -Bg30 -D$COASTRES -Wlightgray -Ir >> $OUT
echo 35 27.3 12 0 0 CM $FILEIR16 | \
	GMT pstext -J -R -O -N >> $OUT


do_reproject "-te 16 -35 20 -31 -ts 400 300"

OUT=testsouthafrica.ps

GMT gmtset GRID_CROSS_SIZE 1 ANNOT_FONT_SIZE_PRIMARY 10

GMT psbasemap -R16/20/-35/-31 -Jm0.8i -B0 -P -K -U"South Africa test" > $OUT
GMT grdimage -Q -R $FILEHRV -C$FILEHRV.cpt -J -O -K >> $OUT
GMT pscoast -R -J -O -K -Bg30 -D$COASTRES -Wlightgray -Ir >> $OUT
echo 18 -30.7 12 0 0 CM $FILEHRV | \
	GMT pstext -J -R -O -K -N >> $OUT

GMT grdimage -Q -R $FILEIR16 -Y5i -C$FILEIR16.cpt -J -O -K >> $OUT
GMT pscoast -R -J -O -K -Bg30 -D$COASTRES -Wlightgray -Ir >> $OUT
echo 18 -30.7 12 0 0 CM $FILEIR16 | \
	GMT pstext -J -R -O -N >> $OUT

rm -f .gmtcommands4 .gmtdefaults4
rm -f $FILEHRV $FILEIR16 $FILEHRV.cpt $FILEIR16.cpt

exit 0

